apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: admin-server
  name: admin-server
  namespace: petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: admin-server
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: admin-server
    spec:
      serviceAccountName: petclinic-msa    
      containers:
        - name: admin-server      
          image: $ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/spring-petclinic-msa/admin-server:latest         
          ports:
            - containerPort: 9090
          resources:
            limits:
              memory: "536870912"
          env:
            - name: eureka.instance.preferIpAddress
              value: "true"          
            - name: JAVA_TOOL_OPTIONS
              value: -javaagent:/opt/aws-opentelemetry-agent.jar          
            - name: OTEL_OTLP_ENDPOINT
              value: "localhost:4317"
            - name: OTEL_RESOURCE
              value: ClusterName=ekslab
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "service.namespace=AWSObservability,service.name=PetClinicAdminServer"
          imagePullPolicy: Always              
        - name: aws-otel-collector
          image: amazon/aws-otel-collector:latest
          env:
            - name: AWS_REGION
              value: $AWS_REGION
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 256m
              memory: 512Mi
            requests:
              cpu: 32m
              memory: 24Mi
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: admin-server
  name: admin-server
  namespace: petclinic
spec:
  ports:
    - name: "9090"
      port: 9090
      targetPort: 9090
  selector:
    io.kompose.service: admin-server
